// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: linkedacc.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalService int32

const (
	ExternalService_Vk ExternalService = 0
	ExternalService_Tg ExternalService = 1
)

// Enum value maps for ExternalService.
var (
	ExternalService_name = map[int32]string{
		0: "Vk",
		1: "Tg",
	}
	ExternalService_value = map[string]int32{
		"Vk": 0,
		"Tg": 1,
	}
)

func (x ExternalService) Enum() *ExternalService {
	p := new(ExternalService)
	*p = x
	return p
}

func (x ExternalService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalService) Descriptor() protoreflect.EnumDescriptor {
	return file_linkedacc_proto_enumTypes[0].Descriptor()
}

func (ExternalService) Type() protoreflect.EnumType {
	return &file_linkedacc_proto_enumTypes[0]
}

func (x ExternalService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalService.Descriptor instead.
func (ExternalService) EnumDescriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{0}
}

type NewExternalPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id поста
	PostId uint64 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// список подключенных сервисов, в которые нужно написать пост
	Ids []*LinkedAccountInp `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *NewExternalPostRequest) Reset() {
	*x = NewExternalPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewExternalPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewExternalPostRequest) ProtoMessage() {}

func (x *NewExternalPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewExternalPostRequest.ProtoReflect.Descriptor instead.
func (*NewExternalPostRequest) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{0}
}

func (x *NewExternalPostRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *NewExternalPostRequest) GetIds() []*LinkedAccountInp {
	if x != nil {
		return x.Ids
	}
	return nil
}

type NewExternalPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewExternalPostResponse) Reset() {
	*x = NewExternalPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewExternalPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewExternalPostResponse) ProtoMessage() {}

func (x *NewExternalPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewExternalPostResponse.ProtoReflect.Descriptor instead.
func (*NewExternalPostResponse) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{1}
}

type GetVkUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUri string `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State       string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *GetVkUrlRequest) Reset() {
	*x = GetVkUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVkUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVkUrlRequest) ProtoMessage() {}

func (x *GetVkUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVkUrlRequest.ProtoReflect.Descriptor instead.
func (*GetVkUrlRequest) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{2}
}

func (x *GetVkUrlRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *GetVkUrlRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetVkUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetVkUrlResponse) Reset() {
	*x = GetVkUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVkUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVkUrlResponse) ProtoMessage() {}

func (x *GetVkUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVkUrlResponse.ProtoReflect.Descriptor instead.
func (*GetVkUrlResponse) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{3}
}

func (x *GetVkUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddVkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUri string `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AddVkRequest) Reset() {
	*x = AddVkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVkRequest) ProtoMessage() {}

func (x *AddVkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVkRequest.ProtoReflect.Descriptor instead.
func (*AddVkRequest) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{4}
}

func (x *AddVkRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AddVkRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AddVkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *LinkedAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *AddVkResponse) Reset() {
	*x = AddVkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVkResponse) ProtoMessage() {}

func (x *AddVkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVkResponse.ProtoReflect.Descriptor instead.
func (*AddVkResponse) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{5}
}

func (x *AddVkResponse) GetAccount() *LinkedAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type AddTgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotToken    string `protobuf:"bytes,1,opt,name=botToken,proto3" json:"botToken,omitempty"`
	ChannelName string `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
}

func (x *AddTgRequest) Reset() {
	*x = AddTgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTgRequest) ProtoMessage() {}

func (x *AddTgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTgRequest.ProtoReflect.Descriptor instead.
func (*AddTgRequest) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{6}
}

func (x *AddTgRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *AddTgRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type AddTgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *LinkedAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *AddTgResponse) Reset() {
	*x = AddTgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTgResponse) ProtoMessage() {}

func (x *AddTgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTgResponse.ProtoReflect.Descriptor instead.
func (*AddTgResponse) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{7}
}

func (x *AddTgResponse) GetAccount() *LinkedAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type LinkedAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId    int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Created    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Name       string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ScreenName string                 `protobuf:"bytes,5,opt,name=screenName,proto3" json:"screenName,omitempty"`
	Service    ExternalService        `protobuf:"varint,6,opt,name=service,proto3,enum=ExternalService" json:"service,omitempty"`
	PhotoUrl   string                 `protobuf:"bytes,7,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
}

func (x *LinkedAccount) Reset() {
	*x = LinkedAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccount) ProtoMessage() {}

func (x *LinkedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccount.ProtoReflect.Descriptor instead.
func (*LinkedAccount) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{8}
}

func (x *LinkedAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkedAccount) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *LinkedAccount) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *LinkedAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkedAccount) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *LinkedAccount) GetService() ExternalService {
	if x != nil {
		return x.Service
	}
	return ExternalService_Vk
}

func (x *LinkedAccount) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type LinkedAccountInp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service ExternalService `protobuf:"varint,2,opt,name=service,proto3,enum=ExternalService" json:"service,omitempty"`
}

func (x *LinkedAccountInp) Reset() {
	*x = LinkedAccountInp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedAccountInp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccountInp) ProtoMessage() {}

func (x *LinkedAccountInp) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccountInp.ProtoReflect.Descriptor instead.
func (*LinkedAccountInp) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{9}
}

func (x *LinkedAccountInp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkedAccountInp) GetService() ExternalService {
	if x != nil {
		return x.Service
	}
	return ExternalService_Vk
}

type GetLinkedAccountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLinkedAccountsRequest) Reset() {
	*x = GetLinkedAccountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountsRequest) ProtoMessage() {}

func (x *GetLinkedAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountsRequest) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{10}
}

type GetLinkedAccountsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts []*LinkedAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (x *GetLinkedAccountsResponse) Reset() {
	*x = GetLinkedAccountsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linkedacc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountsResponse) ProtoMessage() {}

func (x *GetLinkedAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_linkedacc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountsResponse) Descriptor() ([]byte, []int) {
	return file_linkedacc_proto_rawDescGZIP(), []int{11}
}

func (x *GetLinkedAccountsResponse) GetAccounts() []*LinkedAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_linkedacc_proto protoreflect.FileDescriptor

var file_linkedacc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x61, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x56, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x70, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x65, 0x77, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x6b, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x6b, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x56, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x39, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x56, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4c, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x54, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xec, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x34, 0x0a,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x22,
	0x4e, 0x0a, 0x10, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x2a, 0x21, 0x0a, 0x0f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x6b, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x54, 0x67, 0x10, 0x01, 0x32, 0xc2, 0x03, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x61, 0x63, 0x63, 0x12, 0x4c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x6b, 0x55, 0x72,
	0x6c, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6b, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6b, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13,
	0x2f, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x61, 0x63, 0x63, 0x2f, 0x47, 0x65, 0x74, 0x56, 0x6b,
	0x55, 0x72, 0x6c, 0x12, 0x43, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x56, 0x6b, 0x12, 0x0d, 0x2e, 0x41,
	0x64, 0x64, 0x56, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x41, 0x64,
	0x64, 0x56, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x61,
	0x63, 0x63, 0x2f, 0x41, 0x64, 0x64, 0x56, 0x6b, 0x12, 0x43, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x54,
	0x67, 0x12, 0x0d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x4c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x61, 0x63, 0x63, 0x2f, 0x41, 0x64, 0x64, 0x54, 0x67, 0x12, 0x70, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1e, 0x12, 0x1c, 0x2f, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x61, 0x63, 0x63, 0x2f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x6b, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4e, 0x65,
	0x77, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a,
	0x22, 0x1a, 0x2f, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x61, 0x63, 0x63, 0x2f, 0x4e, 0x65, 0x77,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linkedacc_proto_rawDescOnce sync.Once
	file_linkedacc_proto_rawDescData = file_linkedacc_proto_rawDesc
)

func file_linkedacc_proto_rawDescGZIP() []byte {
	file_linkedacc_proto_rawDescOnce.Do(func() {
		file_linkedacc_proto_rawDescData = protoimpl.X.CompressGZIP(file_linkedacc_proto_rawDescData)
	})
	return file_linkedacc_proto_rawDescData
}

var file_linkedacc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_linkedacc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_linkedacc_proto_goTypes = []interface{}{
	(ExternalService)(0),              // 0: ExternalService
	(*NewExternalPostRequest)(nil),    // 1: NewExternalPostRequest
	(*NewExternalPostResponse)(nil),   // 2: NewExternalPostResponse
	(*GetVkUrlRequest)(nil),           // 3: GetVkUrlRequest
	(*GetVkUrlResponse)(nil),          // 4: GetVkUrlResponse
	(*AddVkRequest)(nil),              // 5: AddVkRequest
	(*AddVkResponse)(nil),             // 6: AddVkResponse
	(*AddTgRequest)(nil),              // 7: AddTgRequest
	(*AddTgResponse)(nil),             // 8: AddTgResponse
	(*LinkedAccount)(nil),             // 9: LinkedAccount
	(*LinkedAccountInp)(nil),          // 10: LinkedAccountInp
	(*GetLinkedAccountsRequest)(nil),  // 11: GetLinkedAccountsRequest
	(*GetLinkedAccountsResponse)(nil), // 12: GetLinkedAccountsResponse
	(*timestamppb.Timestamp)(nil),     // 13: google.protobuf.Timestamp
}
var file_linkedacc_proto_depIdxs = []int32{
	10, // 0: NewExternalPostRequest.ids:type_name -> LinkedAccountInp
	9,  // 1: AddVkResponse.account:type_name -> LinkedAccount
	9,  // 2: AddTgResponse.account:type_name -> LinkedAccount
	13, // 3: LinkedAccount.created:type_name -> google.protobuf.Timestamp
	0,  // 4: LinkedAccount.service:type_name -> ExternalService
	0,  // 5: LinkedAccountInp.service:type_name -> ExternalService
	9,  // 6: GetLinkedAccountsResponse.accounts:type_name -> LinkedAccount
	3,  // 7: Linkedacc.GetVkUrl:input_type -> GetVkUrlRequest
	5,  // 8: Linkedacc.AddVk:input_type -> AddVkRequest
	7,  // 9: Linkedacc.AddTg:input_type -> AddTgRequest
	11, // 10: Linkedacc.GetLinkedAccounts:input_type -> GetLinkedAccountsRequest
	1,  // 11: Linkedacc.NewExternalPost:input_type -> NewExternalPostRequest
	4,  // 12: Linkedacc.GetVkUrl:output_type -> GetVkUrlResponse
	6,  // 13: Linkedacc.AddVk:output_type -> AddVkResponse
	8,  // 14: Linkedacc.AddTg:output_type -> AddTgResponse
	12, // 15: Linkedacc.GetLinkedAccounts:output_type -> GetLinkedAccountsResponse
	2,  // 16: Linkedacc.NewExternalPost:output_type -> NewExternalPostResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_linkedacc_proto_init() }
func file_linkedacc_proto_init() {
	if File_linkedacc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linkedacc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewExternalPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewExternalPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVkUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVkUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedAccountInp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linkedacc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linkedacc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linkedacc_proto_goTypes,
		DependencyIndexes: file_linkedacc_proto_depIdxs,
		EnumInfos:         file_linkedacc_proto_enumTypes,
		MessageInfos:      file_linkedacc_proto_msgTypes,
	}.Build()
	File_linkedacc_proto = out.File
	file_linkedacc_proto_rawDesc = nil
	file_linkedacc_proto_goTypes = nil
	file_linkedacc_proto_depIdxs = nil
}
