// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: storage.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachmentType int32

const (
	AttachmentType_photo AttachmentType = 0
	AttachmentType_video AttachmentType = 1
	AttachmentType_file  AttachmentType = 2
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "photo",
		1: "video",
		2: "file",
	}
	AttachmentType_value = map[string]int32{
		"photo": 0,
		"video": 1,
		"file":  2,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

type UploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string         `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Type     AttachmentType `protobuf:"varint,2,opt,name=type,proto3,enum=AttachmentType" json:"type,omitempty"`
	Data     []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadRequest) GetType() AttachmentType {
	if x != nil {
		return x.Type
	}
	return AttachmentType_photo
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attachment *Attachment `protobuf:"bytes,1,opt,name=attachment,proto3" json:"attachment,omitempty"`
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSize int64  `protobuf:"varint,1,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UploadedPartMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalNumberOfBytesUploaded int64 `protobuf:"varint,1,opt,name=TotalNumberOfBytesUploaded,proto3" json:"TotalNumberOfBytesUploaded,omitempty"`
	NumberOfBytesUploaded      int64 `protobuf:"varint,2,opt,name=NumberOfBytesUploaded,proto3" json:"NumberOfBytesUploaded,omitempty"`
}

func (x *UploadedPartMessage) Reset() {
	*x = UploadedPartMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadedPartMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedPartMessage) ProtoMessage() {}

func (x *UploadedPartMessage) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedPartMessage.ProtoReflect.Descriptor instead.
func (*UploadedPartMessage) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UploadedPartMessage) GetTotalNumberOfBytesUploaded() int64 {
	if x != nil {
		return x.TotalNumberOfBytesUploaded
	}
	return 0
}

func (x *UploadedPartMessage) GetNumberOfBytesUploaded() int64 {
	if x != nil {
		return x.NumberOfBytesUploaded
	}
	return 0
}

type MultipartUploadAnyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadReqOneof:
	//
	//	*MultipartUploadAnyRequest_Info
	//	*MultipartUploadAnyRequest_Data
	UploadReqOneof isMultipartUploadAnyRequest_UploadReqOneof `protobuf_oneof:"UploadReqOneof"`
}

func (x *MultipartUploadAnyRequest) Reset() {
	*x = MultipartUploadAnyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadAnyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadAnyRequest) ProtoMessage() {}

func (x *MultipartUploadAnyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadAnyRequest.ProtoReflect.Descriptor instead.
func (*MultipartUploadAnyRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (m *MultipartUploadAnyRequest) GetUploadReqOneof() isMultipartUploadAnyRequest_UploadReqOneof {
	if m != nil {
		return m.UploadReqOneof
	}
	return nil
}

func (x *MultipartUploadAnyRequest) GetInfo() *FileInfo {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadAnyRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *MultipartUploadAnyRequest) GetData() []byte {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadAnyRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isMultipartUploadAnyRequest_UploadReqOneof interface {
	isMultipartUploadAnyRequest_UploadReqOneof()
}

type MultipartUploadAnyRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type MultipartUploadAnyRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*MultipartUploadAnyRequest_Info) isMultipartUploadAnyRequest_UploadReqOneof() {}

func (*MultipartUploadAnyRequest_Data) isMultipartUploadAnyRequest_UploadReqOneof() {}

type MultipartUploadAnyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadRespOneof:
	//
	//	*MultipartUploadAnyResponse_Attachment
	//	*MultipartUploadAnyResponse_UploadedPart
	UploadRespOneof isMultipartUploadAnyResponse_UploadRespOneof `protobuf_oneof:"UploadRespOneof"`
}

func (x *MultipartUploadAnyResponse) Reset() {
	*x = MultipartUploadAnyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadAnyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadAnyResponse) ProtoMessage() {}

func (x *MultipartUploadAnyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadAnyResponse.ProtoReflect.Descriptor instead.
func (*MultipartUploadAnyResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (m *MultipartUploadAnyResponse) GetUploadRespOneof() isMultipartUploadAnyResponse_UploadRespOneof {
	if m != nil {
		return m.UploadRespOneof
	}
	return nil
}

func (x *MultipartUploadAnyResponse) GetAttachment() *Attachment {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadAnyResponse_Attachment); ok {
		return x.Attachment
	}
	return nil
}

func (x *MultipartUploadAnyResponse) GetUploadedPart() *UploadedPartMessage {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadAnyResponse_UploadedPart); ok {
		return x.UploadedPart
	}
	return nil
}

type isMultipartUploadAnyResponse_UploadRespOneof interface {
	isMultipartUploadAnyResponse_UploadRespOneof()
}

type MultipartUploadAnyResponse_Attachment struct {
	Attachment *Attachment `protobuf:"bytes,2,opt,name=attachment,proto3,oneof"`
}

type MultipartUploadAnyResponse_UploadedPart struct {
	UploadedPart *UploadedPartMessage `protobuf:"bytes,3,opt,name=UploadedPart,proto3,oneof"`
}

func (*MultipartUploadAnyResponse_Attachment) isMultipartUploadAnyResponse_UploadRespOneof() {}

func (*MultipartUploadAnyResponse_UploadedPart) isMultipartUploadAnyResponse_UploadRespOneof() {}

type MultipartUploadVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadReqOneof:
	//
	//	*MultipartUploadVideoRequest_FileSize
	//	*MultipartUploadVideoRequest_Data
	UploadReqOneof isMultipartUploadVideoRequest_UploadReqOneof `protobuf_oneof:"UploadReqOneof"`
}

func (x *MultipartUploadVideoRequest) Reset() {
	*x = MultipartUploadVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadVideoRequest) ProtoMessage() {}

func (x *MultipartUploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadVideoRequest.ProtoReflect.Descriptor instead.
func (*MultipartUploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (m *MultipartUploadVideoRequest) GetUploadReqOneof() isMultipartUploadVideoRequest_UploadReqOneof {
	if m != nil {
		return m.UploadReqOneof
	}
	return nil
}

func (x *MultipartUploadVideoRequest) GetFileSize() int64 {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadVideoRequest_FileSize); ok {
		return x.FileSize
	}
	return 0
}

func (x *MultipartUploadVideoRequest) GetData() []byte {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadVideoRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isMultipartUploadVideoRequest_UploadReqOneof interface {
	isMultipartUploadVideoRequest_UploadReqOneof()
}

type MultipartUploadVideoRequest_FileSize struct {
	FileSize int64 `protobuf:"varint,1,opt,name=FileSize,proto3,oneof"`
}

type MultipartUploadVideoRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*MultipartUploadVideoRequest_FileSize) isMultipartUploadVideoRequest_UploadReqOneof() {}

func (*MultipartUploadVideoRequest_Data) isMultipartUploadVideoRequest_UploadReqOneof() {}

type MultipartUploadVideoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadRespOneof:
	//
	//	*MultipartUploadVideoResponse_Attachment
	//	*MultipartUploadVideoResponse_UploadedPart
	UploadRespOneof isMultipartUploadVideoResponse_UploadRespOneof `protobuf_oneof:"UploadRespOneof"`
}

func (x *MultipartUploadVideoResponse) Reset() {
	*x = MultipartUploadVideoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadVideoResponse) ProtoMessage() {}

func (x *MultipartUploadVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadVideoResponse.ProtoReflect.Descriptor instead.
func (*MultipartUploadVideoResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (m *MultipartUploadVideoResponse) GetUploadRespOneof() isMultipartUploadVideoResponse_UploadRespOneof {
	if m != nil {
		return m.UploadRespOneof
	}
	return nil
}

func (x *MultipartUploadVideoResponse) GetAttachment() *Attachment {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadVideoResponse_Attachment); ok {
		return x.Attachment
	}
	return nil
}

func (x *MultipartUploadVideoResponse) GetUploadedPart() *UploadedPartMessage {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadVideoResponse_UploadedPart); ok {
		return x.UploadedPart
	}
	return nil
}

type isMultipartUploadVideoResponse_UploadRespOneof interface {
	isMultipartUploadVideoResponse_UploadRespOneof()
}

type MultipartUploadVideoResponse_Attachment struct {
	Attachment *Attachment `protobuf:"bytes,2,opt,name=attachment,proto3,oneof"`
}

type MultipartUploadVideoResponse_UploadedPart struct {
	UploadedPart *UploadedPartMessage `protobuf:"bytes,3,opt,name=UploadedPart,proto3,oneof"`
}

func (*MultipartUploadVideoResponse_Attachment) isMultipartUploadVideoResponse_UploadRespOneof() {}

func (*MultipartUploadVideoResponse_UploadedPart) isMultipartUploadVideoResponse_UploadRespOneof() {}

type MultipartUploadPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadReqOneof:
	//
	//	*MultipartUploadPhotoRequest_FileSize
	//	*MultipartUploadPhotoRequest_Data
	UploadReqOneof isMultipartUploadPhotoRequest_UploadReqOneof `protobuf_oneof:"UploadReqOneof"`
}

func (x *MultipartUploadPhotoRequest) Reset() {
	*x = MultipartUploadPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadPhotoRequest) ProtoMessage() {}

func (x *MultipartUploadPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadPhotoRequest.ProtoReflect.Descriptor instead.
func (*MultipartUploadPhotoRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (m *MultipartUploadPhotoRequest) GetUploadReqOneof() isMultipartUploadPhotoRequest_UploadReqOneof {
	if m != nil {
		return m.UploadReqOneof
	}
	return nil
}

func (x *MultipartUploadPhotoRequest) GetFileSize() int64 {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadPhotoRequest_FileSize); ok {
		return x.FileSize
	}
	return 0
}

func (x *MultipartUploadPhotoRequest) GetData() []byte {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadPhotoRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isMultipartUploadPhotoRequest_UploadReqOneof interface {
	isMultipartUploadPhotoRequest_UploadReqOneof()
}

type MultipartUploadPhotoRequest_FileSize struct {
	FileSize int64 `protobuf:"varint,1,opt,name=FileSize,proto3,oneof"`
}

type MultipartUploadPhotoRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*MultipartUploadPhotoRequest_FileSize) isMultipartUploadPhotoRequest_UploadReqOneof() {}

func (*MultipartUploadPhotoRequest_Data) isMultipartUploadPhotoRequest_UploadReqOneof() {}

type MultipartUploadPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadRespOneof:
	//
	//	*MultipartUploadPhotoResponse_FileSize
	//	*MultipartUploadPhotoResponse_Attachment
	//	*MultipartUploadPhotoResponse_UploadedPart
	UploadRespOneof isMultipartUploadPhotoResponse_UploadRespOneof `protobuf_oneof:"UploadRespOneof"`
}

func (x *MultipartUploadPhotoResponse) Reset() {
	*x = MultipartUploadPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadPhotoResponse) ProtoMessage() {}

func (x *MultipartUploadPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadPhotoResponse.ProtoReflect.Descriptor instead.
func (*MultipartUploadPhotoResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (m *MultipartUploadPhotoResponse) GetUploadRespOneof() isMultipartUploadPhotoResponse_UploadRespOneof {
	if m != nil {
		return m.UploadRespOneof
	}
	return nil
}

func (x *MultipartUploadPhotoResponse) GetFileSize() int64 {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadPhotoResponse_FileSize); ok {
		return x.FileSize
	}
	return 0
}

func (x *MultipartUploadPhotoResponse) GetAttachment() *Attachment {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadPhotoResponse_Attachment); ok {
		return x.Attachment
	}
	return nil
}

func (x *MultipartUploadPhotoResponse) GetUploadedPart() *UploadedPartMessage {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadPhotoResponse_UploadedPart); ok {
		return x.UploadedPart
	}
	return nil
}

type isMultipartUploadPhotoResponse_UploadRespOneof interface {
	isMultipartUploadPhotoResponse_UploadRespOneof()
}

type MultipartUploadPhotoResponse_FileSize struct {
	FileSize int64 `protobuf:"varint,1,opt,name=FileSize,proto3,oneof"`
}

type MultipartUploadPhotoResponse_Attachment struct {
	Attachment *Attachment `protobuf:"bytes,2,opt,name=attachment,proto3,oneof"`
}

type MultipartUploadPhotoResponse_UploadedPart struct {
	UploadedPart *UploadedPartMessage `protobuf:"bytes,3,opt,name=UploadedPart,proto3,oneof"`
}

func (*MultipartUploadPhotoResponse_FileSize) isMultipartUploadPhotoResponse_UploadRespOneof() {}

func (*MultipartUploadPhotoResponse_Attachment) isMultipartUploadPhotoResponse_UploadRespOneof() {}

func (*MultipartUploadPhotoResponse_UploadedPart) isMultipartUploadPhotoResponse_UploadRespOneof() {}

type MultipartUploadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadReqOneof:
	//
	//	*MultipartUploadFileRequest_FileSize
	//	*MultipartUploadFileRequest_Data
	UploadReqOneof isMultipartUploadFileRequest_UploadReqOneof `protobuf_oneof:"UploadReqOneof"`
}

func (x *MultipartUploadFileRequest) Reset() {
	*x = MultipartUploadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadFileRequest) ProtoMessage() {}

func (x *MultipartUploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadFileRequest.ProtoReflect.Descriptor instead.
func (*MultipartUploadFileRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (m *MultipartUploadFileRequest) GetUploadReqOneof() isMultipartUploadFileRequest_UploadReqOneof {
	if m != nil {
		return m.UploadReqOneof
	}
	return nil
}

func (x *MultipartUploadFileRequest) GetFileSize() int64 {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadFileRequest_FileSize); ok {
		return x.FileSize
	}
	return 0
}

func (x *MultipartUploadFileRequest) GetData() []byte {
	if x, ok := x.GetUploadReqOneof().(*MultipartUploadFileRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isMultipartUploadFileRequest_UploadReqOneof interface {
	isMultipartUploadFileRequest_UploadReqOneof()
}

type MultipartUploadFileRequest_FileSize struct {
	FileSize int64 `protobuf:"varint,1,opt,name=FileSize,proto3,oneof"`
}

type MultipartUploadFileRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*MultipartUploadFileRequest_FileSize) isMultipartUploadFileRequest_UploadReqOneof() {}

func (*MultipartUploadFileRequest_Data) isMultipartUploadFileRequest_UploadReqOneof() {}

type MultipartUploadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to UploadRespOneof:
	//
	//	*MultipartUploadFileResponse_FileSize
	//	*MultipartUploadFileResponse_Attachment
	//	*MultipartUploadFileResponse_UploadedPart
	UploadRespOneof isMultipartUploadFileResponse_UploadRespOneof `protobuf_oneof:"UploadRespOneof"`
}

func (x *MultipartUploadFileResponse) Reset() {
	*x = MultipartUploadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipartUploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadFileResponse) ProtoMessage() {}

func (x *MultipartUploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadFileResponse.ProtoReflect.Descriptor instead.
func (*MultipartUploadFileResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (m *MultipartUploadFileResponse) GetUploadRespOneof() isMultipartUploadFileResponse_UploadRespOneof {
	if m != nil {
		return m.UploadRespOneof
	}
	return nil
}

func (x *MultipartUploadFileResponse) GetFileSize() int64 {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadFileResponse_FileSize); ok {
		return x.FileSize
	}
	return 0
}

func (x *MultipartUploadFileResponse) GetAttachment() *Attachment {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadFileResponse_Attachment); ok {
		return x.Attachment
	}
	return nil
}

func (x *MultipartUploadFileResponse) GetUploadedPart() *UploadedPartMessage {
	if x, ok := x.GetUploadRespOneof().(*MultipartUploadFileResponse_UploadedPart); ok {
		return x.UploadedPart
	}
	return nil
}

type isMultipartUploadFileResponse_UploadRespOneof interface {
	isMultipartUploadFileResponse_UploadRespOneof()
}

type MultipartUploadFileResponse_FileSize struct {
	FileSize int64 `protobuf:"varint,1,opt,name=FileSize,proto3,oneof"`
}

type MultipartUploadFileResponse_Attachment struct {
	Attachment *Attachment `protobuf:"bytes,2,opt,name=attachment,proto3,oneof"`
}

type MultipartUploadFileResponse_UploadedPart struct {
	UploadedPart *UploadedPartMessage `protobuf:"bytes,3,opt,name=UploadedPart,proto3,oneof"`
}

func (*MultipartUploadFileResponse_FileSize) isMultipartUploadFileResponse_UploadRespOneof() {}

func (*MultipartUploadFileResponse_Attachment) isMultipartUploadFileResponse_UploadRespOneof() {}

func (*MultipartUploadFileResponse_UploadedPart) isMultipartUploadFileResponse_UploadRespOneof() {}

type Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId int64          `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Url     string         `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Info    *FileInfo      `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Type    AttachmentType `protobuf:"varint,5,opt,name=type,proto3,enum=AttachmentType" json:"type,omitempty"`
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *Attachment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attachment) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Attachment) GetType() AttachmentType {
	if x != nil {
		return x.Type
	}
	return AttachmentType_photo
}

type AttachmentId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" cql:"id"`                          // @inject_tag: cql:"id"
	OwnerId int64          `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty" cql:"owner_id"` // @inject_tag: cql:"owner_id"
	Type    AttachmentType `protobuf:"varint,3,opt,name=type,proto3,enum=AttachmentType" json:"type,omitempty" cql:"type"`  // @inject_tag: cql:"type"
}

func (x *AttachmentId) Reset() {
	*x = AttachmentId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachmentId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentId) ProtoMessage() {}

func (x *AttachmentId) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentId.ProtoReflect.Descriptor instead.
func (*AttachmentId) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *AttachmentId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttachmentId) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *AttachmentId) GetType() AttachmentType {
	if x != nil {
		return x.Type
	}
	return AttachmentType_photo
}

type GetAttachmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Список id вложений
	Ids []*AttachmentId `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetAttachmentsRequest) Reset() {
	*x = GetAttachmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentsRequest) ProtoMessage() {}

func (x *GetAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *GetAttachmentsRequest) GetIds() []*AttachmentId {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetAttachmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attachments []*Attachment `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
}

func (x *GetAttachmentsResponse) Reset() {
	*x = GetAttachmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentsResponse) ProtoMessage() {}

func (x *GetAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *GetAttachmentsResponse) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

var file_storage_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a,
	0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x42, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e,
	0x0a, 0x1a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x1a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x34,
	0x0a, 0x15, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x22, 0x64, 0x0a, 0x19, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72,
	0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x63, 0x0a, 0x1b, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x10, 0x0a, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x9c, 0x01, 0x0a,
	0x1c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a,
	0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x0c,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x63, 0x0a, 0x1b, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x10,
	0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x22, 0xba, 0x01, 0x0a, 0x1c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x2d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3a,
	0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x62, 0x0a,
	0x1a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x10, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x4f, 0x6e, 0x65, 0x6f,
	0x66, 0x22, 0xb9, 0x01, 0x0a, 0x1b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x2d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3a,
	0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50,
	0x61, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72, 0x74, 0x42, 0x11, 0x0a, 0x0f, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x22, 0x8d, 0x01,
	0x0a, 0x0a, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5e, 0x0a,
	0x0c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2a, 0x30, 0x0a, 0x0e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x10, 0x02, 0x32, 0x96, 0x03, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x53,
	0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1a, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61,
	0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x53, 0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x2e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x13, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x1a, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x41, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x61, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x29, 0x0a, 0x06,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x19, 0x12, 0x17, 0x2f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData = file_storage_proto_rawDesc
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_proto_rawDescData)
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_storage_proto_goTypes = []interface{}{
	(AttachmentType)(0),                  // 0: AttachmentType
	(*UploadRequest)(nil),                // 1: UploadRequest
	(*UploadResponse)(nil),               // 2: UploadResponse
	(*FileInfo)(nil),                     // 3: FileInfo
	(*UploadedPartMessage)(nil),          // 4: UploadedPartMessage
	(*MultipartUploadAnyRequest)(nil),    // 5: MultipartUploadAnyRequest
	(*MultipartUploadAnyResponse)(nil),   // 6: MultipartUploadAnyResponse
	(*MultipartUploadVideoRequest)(nil),  // 7: MultipartUploadVideoRequest
	(*MultipartUploadVideoResponse)(nil), // 8: MultipartUploadVideoResponse
	(*MultipartUploadPhotoRequest)(nil),  // 9: MultipartUploadPhotoRequest
	(*MultipartUploadPhotoResponse)(nil), // 10: MultipartUploadPhotoResponse
	(*MultipartUploadFileRequest)(nil),   // 11: MultipartUploadFileRequest
	(*MultipartUploadFileResponse)(nil),  // 12: MultipartUploadFileResponse
	(*Attachment)(nil),                   // 13: Attachment
	(*AttachmentId)(nil),                 // 14: AttachmentId
	(*GetAttachmentsRequest)(nil),        // 15: GetAttachmentsRequest
	(*GetAttachmentsResponse)(nil),       // 16: GetAttachmentsResponse
}
var file_storage_proto_depIdxs = []int32{
	0,  // 0: UploadRequest.type:type_name -> AttachmentType
	13, // 1: UploadResponse.attachment:type_name -> Attachment
	3,  // 2: MultipartUploadAnyRequest.info:type_name -> FileInfo
	13, // 3: MultipartUploadAnyResponse.attachment:type_name -> Attachment
	4,  // 4: MultipartUploadAnyResponse.UploadedPart:type_name -> UploadedPartMessage
	13, // 5: MultipartUploadVideoResponse.attachment:type_name -> Attachment
	4,  // 6: MultipartUploadVideoResponse.UploadedPart:type_name -> UploadedPartMessage
	13, // 7: MultipartUploadPhotoResponse.attachment:type_name -> Attachment
	4,  // 8: MultipartUploadPhotoResponse.UploadedPart:type_name -> UploadedPartMessage
	13, // 9: MultipartUploadFileResponse.attachment:type_name -> Attachment
	4,  // 10: MultipartUploadFileResponse.UploadedPart:type_name -> UploadedPartMessage
	3,  // 11: Attachment.info:type_name -> FileInfo
	0,  // 12: Attachment.type:type_name -> AttachmentType
	0,  // 13: AttachmentId.type:type_name -> AttachmentType
	14, // 14: GetAttachmentsRequest.ids:type_name -> AttachmentId
	13, // 15: GetAttachmentsResponse.attachments:type_name -> Attachment
	5,  // 16: Storage.MultipartUploadVideo:input_type -> MultipartUploadAnyRequest
	5,  // 17: Storage.MultipartUploadPhoto:input_type -> MultipartUploadAnyRequest
	5,  // 18: Storage.MultipartUploadFile:input_type -> MultipartUploadAnyRequest
	1,  // 19: Storage.Upload:input_type -> UploadRequest
	15, // 20: Storage.GetAttachments:input_type -> GetAttachmentsRequest
	6,  // 21: Storage.MultipartUploadVideo:output_type -> MultipartUploadAnyResponse
	6,  // 22: Storage.MultipartUploadPhoto:output_type -> MultipartUploadAnyResponse
	6,  // 23: Storage.MultipartUploadFile:output_type -> MultipartUploadAnyResponse
	2,  // 24: Storage.Upload:output_type -> UploadResponse
	16, // 25: Storage.GetAttachments:output_type -> GetAttachmentsResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadedPartMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadAnyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadAnyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadVideoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipartUploadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachmentId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttachmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttachmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_storage_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*MultipartUploadAnyRequest_Info)(nil),
		(*MultipartUploadAnyRequest_Data)(nil),
	}
	file_storage_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*MultipartUploadAnyResponse_Attachment)(nil),
		(*MultipartUploadAnyResponse_UploadedPart)(nil),
	}
	file_storage_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*MultipartUploadVideoRequest_FileSize)(nil),
		(*MultipartUploadVideoRequest_Data)(nil),
	}
	file_storage_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*MultipartUploadVideoResponse_Attachment)(nil),
		(*MultipartUploadVideoResponse_UploadedPart)(nil),
	}
	file_storage_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*MultipartUploadPhotoRequest_FileSize)(nil),
		(*MultipartUploadPhotoRequest_Data)(nil),
	}
	file_storage_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*MultipartUploadPhotoResponse_FileSize)(nil),
		(*MultipartUploadPhotoResponse_Attachment)(nil),
		(*MultipartUploadPhotoResponse_UploadedPart)(nil),
	}
	file_storage_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*MultipartUploadFileRequest_FileSize)(nil),
		(*MultipartUploadFileRequest_Data)(nil),
	}
	file_storage_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*MultipartUploadFileResponse_FileSize)(nil),
		(*MultipartUploadFileResponse_Attachment)(nil),
		(*MultipartUploadFileResponse_UploadedPart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_rawDesc = nil
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
